# Supported tokens:
#   {year} {month} {day} {hour} {minute} {second}
#   {millisecond} {microsecond} {timezone}
TIMESTAMP_FORMAT="{year}-{month}-{day} {hour}:{minute}:{second}.{microsecond} {timezone}"
